[package]
name = "kek-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
k256 = { version = "0.13.4", features = ["ecdsa"] }
rand_core = { version = "0.9.3", features = ["std"] }
thiserror = "2.0.12"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
